// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoiseExtensions struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WebtransportCerthashes [][]byte               `protobuf:"bytes,1,rep,name=webtransport_certhashes,json=webtransportCerthashes,proto3" json:"webtransport_certhashes,omitempty"`
	StreamMuxers           []string               `protobuf:"bytes,2,rep,name=stream_muxers,json=streamMuxers,proto3" json:"stream_muxers,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NoiseExtensions) Reset() {
	*x = NoiseExtensions{}
	mi := &file_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseExtensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseExtensions) ProtoMessage() {}

func (x *NoiseExtensions) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseExtensions.ProtoReflect.Descriptor instead.
func (*NoiseExtensions) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

func (x *NoiseExtensions) GetWebtransportCerthashes() [][]byte {
	if x != nil {
		return x.WebtransportCerthashes
	}
	return nil
}

func (x *NoiseExtensions) GetStreamMuxers() []string {
	if x != nil {
		return x.StreamMuxers
	}
	return nil
}

type DntlsClaims struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash is the registration hash of the claimed name.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// fqdn is the full name being claimed.
	Fqdn string `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	// selectors are the selector path hashes of the claimed name.
	Selectors     [][]byte `protobuf:"bytes,3,rep,name=selectors,proto3" json:"selectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DntlsClaims) Reset() {
	*x = DntlsClaims{}
	mi := &file_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DntlsClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DntlsClaims) ProtoMessage() {}

func (x *DntlsClaims) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DntlsClaims.ProtoReflect.Descriptor instead.
func (*DntlsClaims) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{1}
}

func (x *DntlsClaims) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *DntlsClaims) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *DntlsClaims) GetSelectors() [][]byte {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type DntlsNoisePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	IdentitySig   []byte                 `protobuf:"bytes,2,opt,name=identity_sig,json=identitySig,proto3" json:"identity_sig,omitempty"`
	Claims        *DntlsClaims           `protobuf:"bytes,3,opt,name=claims,proto3" json:"claims,omitempty"`
	Extensions    *NoiseExtensions       `protobuf:"bytes,4,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DntlsNoisePayload) Reset() {
	*x = DntlsNoisePayload{}
	mi := &file_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DntlsNoisePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DntlsNoisePayload) ProtoMessage() {}

func (x *DntlsNoisePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DntlsNoisePayload.ProtoReflect.Descriptor instead.
func (*DntlsNoisePayload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{2}
}

func (x *DntlsNoisePayload) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *DntlsNoisePayload) GetIdentitySig() []byte {
	if x != nil {
		return x.IdentitySig
	}
	return nil
}

func (x *DntlsNoisePayload) GetClaims() *DntlsClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *DntlsNoisePayload) GetExtensions() *NoiseExtensions {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_payload_proto protoreflect.FileDescriptor

const file_payload_proto_rawDesc = "" +
	"\n" +
	"\rpayload.proto\x12\bdntls.pb\"o\n" +
	"\x0fNoiseExtensions\x127\n" +
	"\x17webtransport_certhashes\x18\x01 \x03(\fR\x16webtransportCerthashes\x12#\n" +
	"\rstream_muxers\x18\x02 \x03(\tR\fstreamMuxers\"S\n" +
	"\vDntlsClaims\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x12\x1c\n" +
	"\tselectors\x18\x03 \x03(\fR\tselectors\"\xc3\x01\n" +
	"\x11DntlsNoisePayload\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12!\n" +
	"\fidentity_sig\x18\x02 \x01(\fR\videntitySig\x12-\n" +
	"\x06claims\x18\x03 \x01(\v2\x15.dntls.pb.DntlsClaimsR\x06claims\x129\n" +
	"\n" +
	"extensions\x18\x04 \x01(\v2\x19.dntls.pb.NoiseExtensionsR\n" +
	"extensionsB3Z1github.com/libp2p/go-libp2p/p2p/security/dntls/pbb\x06proto3"

var (
	file_payload_proto_rawDescOnce sync.Once
	file_payload_proto_rawDescData []byte
)

func file_payload_proto_rawDescGZIP() []byte {
	file_payload_proto_rawDescOnce.Do(func() {
		file_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)))
	})
	return file_payload_proto_rawDescData
}

var file_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payload_proto_goTypes = []any{
	(*NoiseExtensions)(nil),   // 0: dntls.pb.NoiseExtensions
	(*DntlsClaims)(nil),       // 1: dntls.pb.DntlsClaims
	(*DntlsNoisePayload)(nil), // 2: dntls.pb.DntlsNoisePayload
}
var file_payload_proto_depIdxs = []int32{
	1, // 0: dntls.pb.DntlsNoisePayload.claims:type_name -> dntls.pb.DntlsClaims
	0, // 1: dntls.pb.DntlsNoisePayload.extensions:type_name -> dntls.pb.NoiseExtensions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payload_proto_init() }
func file_payload_proto_init() {
	if File_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_proto_goTypes,
		DependencyIndexes: file_payload_proto_depIdxs,
		MessageInfos:      file_payload_proto_msgTypes,
	}.Build()
	File_payload_proto = out.File
	file_payload_proto_goTypes = nil
	file_payload_proto_depIdxs = nil
}
