syntax = "proto3";
package dntls.pb;

option go_package = "github.com/libp2p/go-libp2p/p2p/security/dntls/pb";

message NoiseExtensions {
  repeated bytes webtransport_certhashes = 1;
  repeated string stream_muxers = 2;
}

message DntlsClaims {
  // hash is the registration hash of the claimed name.
  bytes hash = 1;
  // fqdn is the full name being claimed.
  string fqdn = 2;
  // selectors are the selector path hashes of the claimed name.
  repeated bytes selectors = 3;
}

message DntlsNoisePayload {
  bytes identity_key = 1;
  bytes identity_sig = 2;
  DntlsClaims claims = 3;
  NoiseExtensions extensions = 4;
}
